config/routes.rb
Rails.application.routes.draw do
  
  devise_for :views
devise_for :users
get '/imagenes' => 'images#index'

get '/imagenes/new' => 'images#new', as: 'new_image'

resources :images, only: [:index, :new, :create], path: '/imagenes'

  root to: 'images#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :photo, PhotoUploader
	
	enum category: %w(portrait landscape city\ exploration nature animals)
	#\
	validates :name, presence: true
	

	def tags_text
		self.tags.join('. ')
	end
	
	def tags_text=(value)
		self.tags = value.split(',').map{ |tag| tag.string }
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

before_action :authenticate_user!

  protect_from_forgery with: :exception


end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	
	def index
		@images = Image.all
	end

	def new

		@image = Image.new

	end

	def create

		@image = Image.new secure_params
 
		if @image.save
		  return redirect_to images_path, notice: t('.created', model: @image.class.model_name.human)
        end
  
      render :new
  end

	private
	def secure_params

		params.require(:image).permit :name, :description, :category, :tagss, :photo
	end
end
 #Estoy trabajando en este proyecto que tiene relacion directa con la pagina 500px de echo es una mini version
 #explicare paso a paso detalladamente lo que he aprendeido de los cap. en platzi
 #primero empezamos corriendo una applicacion basica de ruby on rails sin mayor problema
 #algo que no habia echo era cambiar el servido que trae por defecto la app
 # est este caso lo cambiamos a puma aun no se muy bien los beneficios pero tengo entendido que nos
 #brinda mayor ganancia ya q estare realizando una app profesional por lo tanto debo trabajar
 #con los recursos de q dicha app amerita. el servido por defecto es Booting WEBrick
# despues configuramos la base de datos en este caso usamos postgresql con un comando directo
#la inicializamos rails new nuevapp -p postgresql
#de esa manera ya configuramos las base de datos y el servidor
#despues empece por crear mi primera pagina de muestra para cambiar el root welcome#index
#cree un get '/imagenes' => 'imagen'
#estube pendiente del MVC ya que el controller debe estar en plural y el modelo en singular
#images_controller

app/helpers/application_helper.rb
module ApplicationHelper
	def image_categories
		Image.categories.inject({}) do |hash, elem| 
		hash.merge!(t("categories.#{elem.first.gsub(' ', '_')}") => elem.first)
		end
	end	
end

app/views/images/_image.html.erb
<div class='image-box'>
<div class='image-content'>
<%= image_tag image.photo.thumb.url %>
   <h2><%= image.name %></h2>	
</div> 
</div>

app/views/images/create.html.erb
<h1><%= t('.title') %></h1>

app/views/images/index.html.erb
<h1><%= t('.title') %></h1>

<p>
	<%= link_to  t('.new_link'), new_image_path %>
</p>


<section class='images'>
<%= render @images %>
</section>

app/views/images/new.html.erb
<%- model_name = @image.class.model_name.human%>

<h1><%= t('.title', model: model_name) %></h1>

<%= form_for @image, builder: CustomFormBuilder do |form| %>
<%= form.form_error %>

<div class="field">
	
	<%= form.label :name%>
	<%= form.text_field :name%>
	<%= form.field_error :name %>

</div>

<div class="field">
	<%= form.label :decription %>
	<%= form.text_area :decription %>

</div>

<div class="field">
	<%= form.label :category%>
	<%= form.collection_select :category, image_categories, :last, :first%>
</div>

<div class="field">
	<%= form.label :tags%>
	<%= form.text_field :tags%>
</div>

<div class="field">
	<%= form.label :photo%>
	<%= form.file_field :photo%>
</div>

<div class="field">
	<%= form.submit%>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Px500</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='flash'>
 <% flash.each do |key, value| -%>
  <div id="flash-<%= key %>"><%= value %></div>
  <% end -%>
   </div>
   

 <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>



<%= yield %>

</body>
</html>